### PR TITLE
Revise example and documents for sampling

### PR DESCRIPTION
**Pull request by CoreLeader**
* Revise example and documents for sampling

### CODE REVIEW

**Review by Frozenmad — COMMENTED** [review]
Well done! Just some small adjustments~
Besides, can you provide some tutorials about the sampling module? The related files are under `docs/docfile/tutorials`. You can either add new files or revise the model and trainer there.
I think we'd better have:
1. what we have supported and how to use current trainer (for example, give a table to tell user which models are supported with which sampling trainers, and write an easy example to create a solver with sampling trainer inside).
2. how to create customized automodels to use the trainer we've supported.

You can ask other developers to help you writing tutorials if needed~

**Comment by CoreLeader** [comment]
I added a brief introduction about the way to adopt sampling techniques for node classification and rerverted the inappropriate modifications for examples.
However, in my perspective, it is unnecessary to revise the part of model in thr tutorial. First, the current version of that part is sufficiently detailed for an advanced user, who is sufficiently familiar with Python and PyTorch and eligible to do some customization, to create a customized model to meet his/her own demand, and the tutorial is unnecessary to teach the users every detail. If someone would like to do some customization, him/her would checkout and inspect the source code (e.g. `gcn.py`, `gat.py`, `graphsage.py`), and I believe those source files are not very hard to comprehend for an elegible advanced user. Second, the module of `model` is scheduled to be seperated to the encoding stage and decoding stage, thus it is not very necessary to write a detailed totorial on how to customize a legacy style model.
Above all, I am not very capable to make a complement for the model part of tutorial, and I also not very glad to revise that part. Nevertheless, I will be pleased to see some one who is more professional than me to provide a more comprehensive tutorial and document. To be honest, I am not the guy who is very good at writing (natural language literatures), even though perhaps I know a little bit of programming.

**Comment by Frozenmad** [comment]
Thanks for your contribution!
However, I still think we should provide how to create new models since not all users are advanced or have the time to dig deep into the codes. He/she may only want to use the sampling quickly with his/her models. If they figure out that implementing their thoughts have to go through the source codes, they would be scared away. Besides, as we have chosen to publish the codes in current design style, a complete tutorial is a must for our choices and current version, as a conclusion of our work in this develop cycle, and also a respect to the users and the AutoGL project itself. We can never provide a tutorial if we care about what the api or design style would be changed in the future.

Don't worry about not good at tutorials. I'll go through the main logics of current trainer and model later this week to help you complement the current tutorials this time~ You can also learn from other tutorials and it would be a great ability to not only know how to implement, but also know how to let others know your thoughts.

**Comment by Frozenmad** [comment]
Thanks for your contribution!
However, I still think we should provide how to create new models since not all users are advanced or have the time to dig deep into the codes. He/she may only want to use the sampling quickly with his/her models. If they figure out that implementing their thoughts have to go through the source codes, they would be scared away. Besides, as we have chosen to publish the codes in current design style, a complete tutorial is a must for our choices and current version, as a conclusion of our work in this develop cycle, and also a respect to the users and the AutoGL project itself. We can never provide a tutorial if we care about what the api or design style would be changed in the future.

Don't worry about not good at tutorials. I'll go through the main logics of current trainer and model later this week to help you complement the current tutorials this time~ You can also learn from other tutorials and it would be a great ability to not only know how to implement, but also know how to let others know your thoughts.

**Comment by Frozenmad** [comment]
I may not have time recently, so you can try to complete on yourself before I get on hand~

**Pull request merged**
