### PR TITLE
revise model tutorial

### PR DESCRIPTION
**Pull request by Frozenmad**

### CODE REVIEW

**Comment by Frozenmad** [comment]
Hi @CoreLeader , please help check whether the model tutorial is correct, especially the part related to sampling. Also, if you think the trainer tutorial need revised, you can override it in the same style~

**Comment by CoreLeader** [comment]
First of all, I would like to convey my sincere apologize for late reply, because that I am preparing for a coding interview to be held recently.
Good job! The majority of your modification are impressive, I just did a little bit revision.
The words *mendatory* and *mandatory* have different meanings, take a look at dictionary for more details. I replaced the *mendatory* (possibly a typo for word *mandatory*) with *required*. The expression pair `optional <-> required` is more commonly used in programming.

**Review by CoreLeader — APPROVED** [review]

**Comment by Frozenmad** [comment]
Hi @CoreLeader ,

I've tested the codes inside current tutorial, and find that currently the sampling part doesn't work. Can you help fixing the bugs?

I use the following code snippets:

```python
# code.py
import sys
sys.path.append('../')
import torch
from autogl.module.model import BaseModel
from autogl.solver import AutoNodeClassifier
import autogl
from autogl.module.model.base import ClassificationSupportedSequentialModel

# override Linear so that it can take graph data as input
class Linear(torch.nn.Linear):
    def forward(self, data):
        return super().forward(data.x)

class MyMLPSampling(ClassificationSupportedSequentialModel):
    def __init__(self, in_channels, num_classes, layer_num, dim):
        super().__init__()
        if layer_num == 1:
            ops = [Linear(in_channels, num_classes)]
        else:
            ops = [Linear(in_channels, dim)]
            for i in range(layer_num - 2):
                ops.append(Linear(dim, dim))
            ops.append(Linear(dim, num_classes))

        self.core = torch.nn.ModuleList(ops)

    # (required) override sequential_encoding_layers property to interact with sampling
    @property
    def sequential_encoding_layers(self) -> torch.nn.ModuleList:
        return self.core

    # (required) define the encode logic of classification for sampling
    def cls_encode(self, data):
        # if you use sampling, the data will be passed in two possible ways,
        # you can judge it use following rules
        if hasattr(data, 'edge_indexes'):
            # the edge_indexes are a list of edge_index, one for each layer
            edge_indexes = data.edge_indexes
            edge_weights = [None] * len(self.core) if getattr(data, 'edge_weights', None) is None else data.edge_weights
        else:
            # the edge_index and edge_weight will stay the same as default
            edge_indexes = [data.edge_index] * len(self.core)
            edge_weights = [getattr(data, 'edge_weight', None)] * len(self.core)

        x = data.x
        for i in range(len(self.core)):
            data = autogl.data.Data(x=x, edge_index=edge_indexes[i])
            data.edge_weight = edge_weights[i]
            x = self.sequential_encoding_layers[i](data)
        return x

    # (required) define the decode logic of classification for sampling
    def cls_decode(self, x):
        return torch.nn.functional.log_softmax(x)

# define your automodel, need to inherit from BaseModel
class MyAutoMLP(BaseModel):
    def __init__(self):
        # (required) make sure you call __init__ of super with init argument properly set.
        # if you do not want to initialize inside __init__, please pass False.
        super().__init__(init=False)

        # (required) define the search space
        self.space = [
            {'parameterName': 'layer_num', 'type': 'INTEGER', 'minValue': 1, 'maxValue': 5, 'scalingType': 'LINEAR'},
            {'parameterName': 'dim', 'type': 'INTEGER', 'minValue': 64, 'maxValue': 128, 'scalingType': 'LINEAR'}
        ]

        # set default hyper-parameters
        self.layer_num = 2
        self.dim = 72

        # for the hyper-parameters that are related with dataset, you can just set them to None
        self.num_classes = None
        self.num_features = None

        # (required) since we don't know the num_classes and num_features until we see the dataset,
        # we cannot initialize the models when instantiated. the initialized will be set to False.
        self.initialized = False

        # (required) set the device of current auto model
        self.device = torch.device('cuda')

    # (required) get current hyper-parameters of this automodel
    # need to return a dictionary whose keys are the same with self.space
    def get_hyper_parameter(self):
        return {
            'layer_num': self.layer_num,
            'dim': self.dim
        }

    # (required) override to interact with num_classes
    def get_num_classes(self):
        return self.num_classes

    # (required) override to interact with num_classes
    def set_num_classes(self, n_classes):
        self.num_classes = n_classes

    # (required) override to interact with num_features
    def get_num_features(self):
        return self.num_features

    # (required) override to interact with num_features
    def set_num_features(self, n_features):
        self.num_features = n_features

    # (required) instantiate the core MLP model using corresponding hyper-parameters
    def initialize(self):
        # (required) you need to make sure the core model is named as `self.model`
        self.model = MyMLPSampling(
            in_channels = self.num_features,
            num_classes = self.num_classes,
            layer_num = self.layer_num,
            dim = self.dim
        ).to(self.device)

        self.initialized = True

    # (required) override to create a copy of model using provided hyper-parameters
    def from_hyper_parameter(self, hp):
        # hp is a dictionary that contains keys and values corrsponding to your self.space
        # in this case, it will be in form {'layer_num': XX, 'dim': XX}

        # create a new instance
        ret = self.__class__()

        # set the hyper-parameters related to dataset and device
        ret.num_classes = self.num_classes
        ret.num_features = self.num_features
        ret.device = self.device

        # set the hyper-parameters according to hp
        ret.layer_num = hp['layer_num']
        ret.dim = hp['dim']

        # initialize it before returning
        ret.initialize()

        return ret

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--trainer', type=str, default='NodeClassificationGraphSAINTTrainer', choices=['NodeClassificationGraphSAINTTrainer', 'NodeClassificationLayerDependentImportanceSamplingTrainer', 'NodeClassificationNeighborSamplingTrainer'])

args = parser.parse_args()

solver = AutoNodeClassifier(graph_models=(MyAutoMLP(),), device='cuda', default_trainer=args.trainer)
from autogl.datasets import build_dataset_from_name
cora = build_dataset_from_name('cora')
solver.fit(cora)

```

The error message or bugs are described below:

Running
```cmd
python code.py --trainer NodeClassificationGraphSAINTTrainer
```
get error:
```logs
File "../autogl/solver/classifier/node_classifier.py", line 418, in fit
    trainer=model, dataset=self.dataset, time_limit=time_for_each_model
  File "../autogl/module/hpo/advisorbase.py", line 166, in optimize
    current_trainer, perf = fn(decoded_json)
  File "../autogl/module/hpo/advisorbase.py", line 145, in fn
    current_trainer.train(dataset)
  File "../autogl/module/train/node_classification_trainer/node_classification_sampled_trainer.py", line 539, in train
    self.__train_only(data)
  File "../autogl/module/train/node_classification_trainer/node_classification_sampled_trainer.py", line 276, in __train_only
    num_workers=self.__training_sampler_num_workers
  File "../autogl/module/train/sampling/sampler/graphsaint_sampler.py", line 85, in create_edge_sampler
    num_graphs_per_epoch, sample_coverage_factor, log=False, **kwargs
  File "//python/lib/python3.6/site-packages/torch_geometric/data/graph_saint.py", line 82, in __init__
    self.node_norm, self.edge_norm = self.__compute_norm__()
  File "//python/lib/python3.6/site-packages/torch_geometric/data/graph_saint.py", line 140, in __compute_norm__
    for data in loader:
  File "//python/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "//python/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 737, in __init__
    w.start()
  File "//python/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "//python/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "//python/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "//python/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "//python/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "//python/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "//python/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'GraphSAINTSampler.__compute_norm__.<locals>.<lambda>'
```

Running
``` cmd
python code.py --trainer NodeClassificationGraphSAINTTrainer
```
and the error is:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "//python/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "//python/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "//python/lib/python3.6/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "//python/lib/python3.6/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "//python/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "//python/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "//python/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "code.py", line 152, in <module>
    solver.fit(cora)
  File "../autogl/solver/classifier/node_classifier.py", line 418, in fit
    trainer=model, dataset=self.dataset, time_limit=time_for_each_model
  File "../autogl/module/hpo/advisorbase.py", line 166, in optimize
    current_trainer, perf = fn(decoded_json)
  File "../autogl/module/hpo/advisorbase.py", line 145, in fn
    current_trainer.train(dataset)
  File "../autogl/module/train/node_classification_trainer/node_classification_sampled_trainer.py", line 1176, in train
    self.__train_only(data)
  File "../autogl/module/train/node_classification_trainer/node_classification_sampled_trainer.py", line 836, in __train_only
    for sampled_data in __layer_dependent_importance_sampler:
  File "../autogl/module/train/sampling/sampler/target_dependant_sampler.py", line 153, in __iter__
    return super(TargetDependantSampler, self).__iter__()
  File "//python/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "//python/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 737, in __init__
    w.start()
  File "//python/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "//python/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "//python/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "//python/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "//python/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "//python/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "//python/lib/python3.6/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "//python/lib/python3.6/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

When running
```
python code.py --trainer NodeClassificationNeighborSamplingTrainer
```

The error is:
```
Traceback (most recent call last):
  File "code.py", line 152, in <module>
    solver.fit(cora)
  File "../autogl/solver/classifier/node_classifier.py", line 418, in fit
    trainer=model, dataset=self.dataset, time_limit=time_for_each_model
  File "../autogl/module/hpo/advisorbase.py", line 166, in optimize
    current_trainer, perf = fn(decoded_json)
  File "../autogl/module/hpo/advisorbase.py", line 145, in fn
    current_trainer.train(dataset)
  File "../autogl/module/train/node_classification_trainer/node_classification_sampled_trainer.py", line 1800, in train
    self.__train_only(data)
  File "../autogl/module/train/node_classification_trainer/node_classification_sampled_trainer.py", line 1464, in __train_only
    num_workers=self.__training_sampler_num_workers
  File "../autogl/module/train/sampling/sampler/neighbor_sampler.py", line 83, in __init__
    edge_index, list(sampling_sizes[::-1]), target_nodes_indexes,
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Frozenmad** [comment]
I've gone through the logic of `NodeClassificationNeighborSamplingTrainer`, and find that `sample_sizes` in `**kwargs` do not have default parameters, and should be a list that is equal to the length of model.
I think this design may not work well since the layer number of models can change during hpo and we cannot set `sample_sizes` as a given fixed hyperparamter.
In my local version, I've now change the `sample_sizes` to `sample size` and expand it to a list according to the layer number of current model. And add the following line in `code.py` following the examples you provide:
```
torch.multiprocessing.set_sharing_strategy('file_system')
```

By the way, I think this line should be made clear in tutorial.

After setting the default `sampling_size` to `2` and lower the epochs. I've managed to run the example, but at a very low speed (100s per experiments). Is the speed normal?

Also, do you think we make it a given fixed hyperparamter for `sampling_size` or a searchable hp and give it to hpo?
I recommend the former for now for quick bug fix.

**Comment by CoreLeader** [comment]
1. For GraphSAINT, the hyper-parameter `training_sampler_num_workers` must be set as `0` to use single process instead of multi process. This limitation is owing to the GraphSAINT implementation provided by PyTorch-Geometric.
2. I have search some information about the following runtime error:
> RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase.
Maybe the expressions to be executed in main process should be placed in `if __name__ == '__main__':`, like the examples to avoid some multiprocess issue.
3. For Node-wise sampling, the hyper-parameter `sample_sizes` can be set as a *NUMERICAL_LIST* with `cutFunc` and `cutParam`, the `cutParam` can be set as `num_layer` in **provided** hyper-parameter space, but I do NOT recommend to hard program the default HP space in trainer, because that means the default HP space is dependant to a `num_layer` HP to be assumed existing.
Definitely, both the Layer-wise sampling and the Node-wise Sampling require the HP of sampling sizes, although the names vary.

**Comment by Frozenmad** [comment]
As you have mentioned, I've also find that the bugs in `NodeClassificationLayerDependentImportanceSamplingTrainer` are owning to no default hp in `sampled_node_sizes`. I also notice that there are no default hp space (default to []) in current implementation, which may means that users cannot directly use `default_trainer=a_str_describing_sample_trainer`. How do we fix these bugs?

**Comment by Frozenmad** [comment]
> As you have mentioned, I've also find that the bugs in `NodeClassificationLayerDependentImportanceSamplingTrainer` are owning to no default hp in `sampled_node_sizes`. I also notice that there are no default hp space (default to []) in current implementation, which may means that users cannot directly use `default_trainer=a_str_describing_sample_trainer`. How do we fix these bugs?

I remember that user can also set the `trainer_hp_space` in `solver`. We may force user to set this parameters when sampling trainer is used.

**Comment by CoreLeader** [comment]
No, this is not an issue on default HP space. We can explain in tutorial that user MUST assign hyper parameter space for node classification with sampling. The more substantial reason is the logic is that the model have to declare the length of `edge_indexes` and `edge_weights` it requires for trainer, thus there is not an available default hyper parameter space for trainer. The trainer must have some way to "realize" or "recognize" the number of layers it should sample, the most direct way for this requirement is that user should specify `sampling_size` or `sampled_node_sizes` specifically in YAML configuration or in source code they implement (we can provide an example).
After all, we should reconsider the design assumption that *everything has an default value so that user can user this utility without any specification*. Owing to the development of AutoML, we still can not achieve this graceful dream. I have also read some literatures on "dynamically expanding scale of model during training", but this is another issue, and they also have their limitations.

**Comment by CoreLeader** [comment]
> > As you have mentioned, I've also find that the bugs in `NodeClassificationLayerDependentImportanceSamplingTrainer` are owning to no default hp in `sampled_node_sizes`. I also notice that there are no default hp space (default to []) in current implementation, which may means that users cannot directly use `default_trainer=a_str_describing_sample_trainer`. How do we fix these bugs?
> 
> I remember that user can also set the `trainer_hp_space` in `solver`. We may force user to set this parameters when sampling trainer is used. We need to make this clear in our tutorial.

Wow! It is an amazing design of solver. I also think this is a feasible solution. In addition, the `num_workers` for GraphSAINT sampler can be set as `0` very simply.
I just have some requests, can you please decalare the requirement you proposed in tutorial? Since I am not so familiar with solver module, and I believe you have gone through trainer with sampling and you know the hyperparameters the trainers require. Besides, as I have mentioned before, I am preparing for an coding interview to be held in July 13, maybe I am able to revise the tutorial after that, as the interview is a little bit urgent for myself.

**Comment by Frozenmad** [comment]
Please focus on the code interview for now :). I'll try my best to give a new version for trainer tutorial~ Still the revision may need you to review for correctness~ 

Best wishes to your interview~

**Comment by Frozenmad** [comment]
@CoreLeader Can you check whether the modifications are proper?

**Comment by Frozenmad** [comment]
@CoreLeader Can you check whether the modifications are proper?

**Comment by CoreLeader** [comment]
> @CoreLeader Can you check whether the modifications are proper?

Yes, it is correct. You are XIN KU. Respect for your devotion and contribution!

**Pull request merged**
